import { FormEvent, useEffect, useMemo, useState } from 'react';
import type { ColumnDef } from '@tanstack/react-table';
import { CheckCircle2, DatabaseBackup, FolderOpen, Loader2, RotateCcw, ShieldCheck } from 'lucide-react';
import { toast } from 'sonner';
import { DataTable } from '@/components/DataTable';
import { Badge } from '@/components/ui/Badge';
import { Button } from '@/components/ui/Button';
import { Card, CardTitle } from '@/components/ui/Card';
import { Input } from '@/components/ui/Input';
import { backupDatabase, listBackupLogs, scheduleRestore, verifyBackup } from '@/services/schoolApi';
import type { BackupLog } from '@/types';

export function BackupRestore(){
 const [logs,setLogs]=useState<BackupLog[]>([]); const [target,setTarget]=useState(''); const [restorePath,setRestorePath]=useState(''); const [busy,setBusy]=useState(false); const [verify,setVerify]=useState<{ok:boolean;tables:number;message:string}|undefined>();
 async function load(){setLogs(await listBackupLogs());} useEffect(()=>{load()},[]);
 async function runBackup(){setBusy(true);try{const path=await backupDatabase(target);toast.success(`Backup created: ${path}`);await load();}catch(e){toast.error(String(e));}finally{setBusy(false);}}
 async function checkRestore(e:FormEvent){e.preventDefault(); if(!restorePath.trim())return toast.error('Backup path required'); setBusy(true); try{const res=await verifyBackup(restorePath); setVerify(res); res.ok?toast.success(res.message):toast.error(res.message);}catch(e){toast.error(String(e));}finally{setBusy(false);}}
 async function doSchedule(){if(!restorePath.trim())return; if(!confirm('Schedule restore? Current database will be replaced on next app start.'))return; setBusy(true); try{const msg=await scheduleRestore(restorePath); toast.success(msg);}catch(e){toast.error(String(e));}finally{setBusy(false);}}
 const columns=useMemo<ColumnDef<BackupLog>[]>(()=>[{header:'Date',accessorKey:'createdAt'},{header:'Type',accessorKey:'backupType'},{header:'Path',cell:({row})=><span className="break-all text-xs">{row.original.backupPath}</span>},{header:'Size',cell:({row})=>`${Math.round(Number(row.original.fileSize||0)/1024)} KB`},{header:'Verified',cell:({row})=><Badge>{row.original.verified?'OK':'Warning'}</Badge>},{header:'Status',accessorKey:'status'},{header:'Message',accessorKey:'message'}],[]);
 return <div className="space-y-5"><div><h2 className="text-3xl font-black">Backup / Restore</h2><p className="text-slate-500">Manual full ZIP backups, restore preview and backup logs. Backup includes local SQLite database and student photos.</p></div><div className="grid gap-4 md:grid-cols-3"><Card><CardTitle>Total Backups</CardTitle><p className="mt-2 text-3xl font-black">{logs.length}</p></Card><Card><CardTitle>Verified</CardTitle><p className="mt-2 text-3xl font-black text-emerald-600">{logs.filter(l=>l.verified).length}</p></Card><Card><CardTitle>Last Backup</CardTitle><p className="mt-2 text-sm font-bold">{logs[0]?.createdAt||'No backup yet'}</p></Card></div><div className="grid gap-5 lg:grid-cols-2"><Card><CardTitle className="flex items-center gap-2"><DatabaseBackup size={20}/> Manual Backup</CardTitle><p className="mt-2 text-sm text-slate-500">Leave folder blank to save inside app data backups folder. Or paste a folder path.</p><div className="mt-4 space-y-3"><Input value={target} onChange={e=>setTarget(e.target.value)} placeholder="Optional target folder e.g. D:\\SchoolERPBackups"/><Button onClick={runBackup} disabled={busy}>{busy&&<Loader2 className="h-4 w-4 animate-spin"/>}<DatabaseBackup size={18}/> Create Full Backup</Button></div></Card><Card><CardTitle className="flex items-center gap-2"><RotateCcw size={20}/> Restore Preview</CardTitle><form onSubmit={checkRestore} className="mt-4 space-y-3"><Input value={restorePath} onChange={e=>setRestorePath(e.target.value)} placeholder="Paste backup .sqlite3 path"/><div className="flex flex-wrap gap-2"><Button disabled={busy}><ShieldCheck size={18}/> Verify Backup</Button><Button type="button" onClick={doSchedule} disabled={busy||!verify?.ok} className="bg-amber-600 hover:bg-amber-700"><RotateCcw size={18}/> Schedule Restore</Button></div></form>{verify&&<div className={`mt-4 rounded-xl p-3 text-sm font-semibold ${verify.ok?'bg-emerald-50 text-emerald-700 dark:bg-emerald-950 dark:text-emerald-300':'bg-red-50 text-red-700 dark:bg-red-950 dark:text-red-300'}`}><div className="flex items-center gap-2"><CheckCircle2 size={18}/> {verify.message}</div><p>Tables found: {verify.tables}</p></div>}</Card></div><Card><CardTitle>Backup Policy Foundation</CardTitle><div className="mt-3 grid gap-3 md:grid-cols-3"><div className="rounded-xl bg-slate-50 p-3 dark:bg-slate-800"><b>Daily Auto Backup</b><p className="text-sm text-slate-500">Setting-ready; scheduler can be enabled at app startup.</p></div><div className="rounded-xl bg-slate-50 p-3 dark:bg-slate-800"><b>Weekly / Monthly</b><p className="text-sm text-slate-500">Folder and retention rules are ready for Settings integration.</p></div><div className="rounded-xl bg-slate-50 p-3 dark:bg-slate-800"><b>Includes</b><p className="text-sm text-slate-500">SQLite database + photos folder included in full ZIP backup.</p></div></div></Card><DataTable data={logs} columns={columns}/></div>;
}
